name: CI Tests

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ro-dou
      uses: actions/checkout@v3
      with:
        path: Ro-dou

    - name: Run docker-compose
      run: cd Ro-dou && make run

    - name: run tests
      run: cd Ro-dou && make tests
