name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ro-dou
      uses: actions/checkout@v2
      with:
        path: Ro-dou

    - name: Install dependencies
      run: make install-deps

    - name: Run docker-compose
      run: make up

    - name: run tests
      run: make tests
