# TODO

name: Create Ro-DOU documentation pages with MkDocs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs

      - name: Build MkDocs site
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml -b gh-pages
